# Project: Intelligent Retail (Edge Model)
### Datum: 2026-03-15
### Team: Michal Kakol

## 0. Setup:

In [1]:
import logging
import os
import pandas as pd
from PIL import Image
import pickle
import hashlib
import json
from datetime import datetime
logging.basicConfig(level=logging.INFO)
from functions.edge import *
from functions.cloud import *

## 1. Data Loading:

### 1.1. Edge:

In [2]:
images = edge_load_images("../data/raw/image/frames")

Loaded images: 2000

In [3]:
labels, df_labels = edge_load_labels("../data/raw/image/labels.csv")
df_labels.head()

Loaded labels: 2000

   id  count
0   1     35
1   2     41
2   3     41
3   4     44
4   5     41

In [4]:
edge_validate(images, labels)

Number of images: 2000
Number of labels: 2000

### 1.2. Cloud:

In [5]:
df = cloud_load_data("../data/raw/text/train.csv")
df.head()

        date  store  item  sales
0 2013-01-01      1     1     13
1 2013-01-02      1     1     11
2 2013-01-03      1     1     14
3 2013-01-04      1     1     13
4 2013-01-05      1     1     10

In [6]:
cloud_validate(df)

Shape: (913000, 4)
Null:
 date     0
store    0
item     0
sales    0
dtype: int64
Negatives: 0

## 2. Data Processing:

### 2.1. Edge:

In [7]:
processed_images = edge_preprocess_images(images)

Processed images: 2000

In [8]:
edge_save_data(processed_images, "../data/processed/images.pkl")

### 2.2. Cloud:

In [9]:
df_transformed = cloud_transform(df)
df_transformed.head()

        date  store  item  sales  day_of_week  month
0 2013-01-01      1     1     13            1      1
1 2013-01-02      1     1     11            2      1
2 2013-01-03      1     1     14            3      1
3 2013-01-04      1     1     13            4      1
4 2013-01-05      1     1     10            5      1

In [10]:
cloud_save_data(df_transformed, "../data/processed/sales.parquet")

In [11]:
cloud_validate_output("../data/processed/sales.parquet")

Validated shape: (913000, 6)
        date  store  item  sales  day_of_week  month
0 2013-01-01      1     1     13            1      1
1 2013-01-02      1     1     11            2      1
2 2013-01-03      1     1     14            3      1
3 2013-01-04      1     1     13            4      1
4 2013-01-05      1     1     10            5      1

             date  store  item  sales  day_of_week  month
0      2013-01-01      1     1     13            1      1
1      2013-01-02      1     1     11            2      1
2      2013-01-03      1     1     14            3      1
3      2013-01-04      1     1     13            4      1
4      2013-01-05      1     1     10            5      1
...           ...    ...   ...    ...          ...    ...
912995 2017-12-27     10    50     63            2     12
912996 2017-12-28     10    50     59            3     12
912997 2017-12-29     10    50     74            4     12
912998 2017-12-30     10    50     62            5     12
912999 2017-12-31     10    50     82            6     12

[913000 rows x 6 columns]

## 3. Pipeline:

### 3.1. Edge:

In [12]:
edge_pipeline()

INFO:root:Running edge pipeline

Loaded images: 2000
Loaded labels: 2000
Number of images: 2000
Number of labels: 2000
Edge stats: {'timestamp': '2026-03-25T19:00:43.412401', 'image_count': 2000, 'label_count': 2000, 'label_mean': 31.1575, 'label_min': 13, 'label_max': 53}
Processed images: 2000

INFO:root:Edge pipeline finished

### 3.1. Cloud:

In [13]:
cloud_pipeline()

INFO:root:Running cloud pipeline

Shape: (913000, 4)
Null:
 date     0
store    0
item     0
sales    0
dtype: int64
Negatives: 0
Cloud stats: {'timestamp': '2026-03-25T19:01:03.656026', 'row_count': 913000, 'sales_mean': 52.250286966046005, 'sales_std': 28.801143603526242, 'sales_min': 0, 'sales_max': 231, 'date_range': ['2013-01-01 00:00:00', '2017-12-31 00:00:00'], 'store_count': 10, 'item_count': 50}

INFO:root:Cloud pipeline finished

Validated shape: (913000, 6)
        date  store  item  sales  day_of_week  month
0 2013-01-01      1     1     13            1      1
1 2013-01-02      1     1     11            2      1
2 2013-01-03      1     1     14            3      1
3 2013-01-04      1     1     13            4      1
4 2013-01-05      1     1     10            5      1